[package]
name = "sigma-ec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
hmac = "0.12.1"

aes = "0.8.2"

rand_chacha = "0.3.1"
rand = "0.8.4"

curve25519-dalek = "3"
